apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coffee-diary.fullname" . }}-config
  labels:
    {{- include "coffee-diary.labels" . | nindent 4 }}
data:
  database.host: {{ include "coffee-diary.database.host" . | quote }}
  database.port: {{ include "coffee-diary.database.port" . | quote }}
  database.name: {{ include "coffee-diary.database.name" . | quote }}
